name: Deploy on AWS
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest Repo
              uses: actions/checkout@master

            - name: Generate deployment package
              run: zip -r deploy.zip * -x "**node_modules"

            # - name: Get timestamp
            #   uses: gerred/actions/current-time@master
            #   id: current-time

            # - name: Run string remplacement
            #   uses: frabert/replace-string-action@master
            #   id: format-time
            #   with:
            #     pattern: '[:\.]+'
            #     string: "${{steps.current-time.outputs.time}}"
            #     replace-with: '-'
            #     flags: 'g'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v14
              with: 
                aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                application_name: simple-react-gh
                environment_name: Simple-react-gh-env
                version_label: "simple-react-deployment"
                region: us-east-2
                deployment_package: deploy.zip